#
# Note: postgresql support is only for local agent development, NOT for local server side development.
# There are still bugs at server side when it's used as storage, but these bugs are trivial for agent development.
#
bithon:
  storage:
    tracing:
      enabled: true
      provider: postgres-local
      ttl:
        enabled: true
        ttl: P1D
        cleanPeriod: PT1M
      indexes:
        # A demo of how the index works, can be removed in production
        map:
          "[http.method]": 1

    metric:
      enabled: true
      provider: postgres-local
      ttl:
        enabled: true
        ttl: P1D
        cleanPeriod: PT1M

    event:
      enabled: true
      provider: postgres-local
      ttl:
        enabled: true
        ttl: P1D
        cleanPeriod: PT1M

    meta:
      enabled: true
      provider: postgres-local
      ttl:
        enabled: true
        ttl: PT5M
        cleanPeriod: PT1M

    setting:
      enabled: true
      provider: postgres-local

    dashboard:
      enabled: true
      provider: postgres-local

    alerting:
      all:
        provider: postgres-local
        ttl:
          enabled: true
          ttl: P1D
          cleanPeriod: PT3M

      log:
        provider: postgres-local
        ttl:
          enabled: true
          ttl: P1D
          cleanPeriod: PT3M

    providers:
      # start postgresql in docker with the following command to test:
      #   docker run --name postgres -e POSTGRES_USER=root -e POSTGRES_PASSWORD=root -p 5432:5432 -d postgres
      #   docker exec -it postgres psql -U root -c "CREATE DATABASE bithon;"
      #   docker exec -it postgres psql -U root -d bithon OR docker exec -it postgres psql -U root and then '\c bithon' to switch database
      # use \d
      postgres-local:
        type: postgresql
        url: jdbc:postgresql://localhost:5432/bithon
        driverClassName: org.postgresql.Driver
        username: root
        password: root

